spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(UGndU3lx2AdAtuUBkeDqoZNFWNVtiLKgCb4VNNobbK9khWEsKypyQgRfyc5gNbyWjCPYowzsLH3b+S4W5b8YR4AvNwmOkhFihe3+gXI4GgWHdjopECQldkFLaJBRR9HFl2Ir6fQydv6ENNImswxwCaBuAYBQJK9AyW1/l0PXE3ETuM+MR9fVj2u8lZdeYntG)
    username: ENC(mf26xrSdlsDGLOp2uRVtYQ==)
    password: ENC(B9/bakG1kuaw3NeCNI4dq6K/zkFiyO7uSWx6IR7jUQA=)

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
    hibernate:
      ddl-auto: validate
    generate-ddl: false