spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(gnyYY2my5ZaFbvuc1ShsFN8N/6HyTS1sQ5UD+qe72zTg/xZCwIDJsttUCG56/ZZfmIRoFEy6c0gJgFE1FhmB9lYNO9nGF2bf8F75TJqccuicBum0mkyqp30RmK7tC4VoKmHw97c6MRAyx3Iv7LagNw==)
    username: ENC(mf26xrSdlsDGLOp2uRVtYQ==)
    password: ENC(B9/bakG1kuaw3NeCNI4dq6K/zkFiyO7uSWx6IR7jUQA=)

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
    hibernate:
      ddl-auto: create
    generate-ddl: true