cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ENC(QgbAPht1L93mXhoIZP6Ud0/E6ZE43Hjh4AHjY40IIPw=)
      secret-key: ENC(160fSjzHjr+WlualFQLy+0zBnIz9cnA+5lgrND4TyaaYOC759gMuH38luM9A1t1nYXnKvibPQNc=)
    s3:
      bucket: ENC(Yn+dhp+Db9HHEcIktA2umG1VxK0Zr3Nl)


