spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(sA1qQk9QtqoPqEJkgh0yUSh8NIhMgmnYJgW0GYQRmnGLMPBh2vVR1pAyD3SUQOMoKMM2ZsyLnz7Btl1u0kMbbXIEpuh4OmyfQ0QmAHeaYBa/RSjc3pY3+x29SVHOwAUo0xyDCq3VUu/urs6Qt0VUduPNFS0RnHJg)
    username: ENC(Ue2fqsFH4tufRUGznOeZgA==)
    password: ENC(sb6mOsr7dFp5iQiIZ0rd3x1iV6qlQJuX)

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect