spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(3HaL7KseKUVsXdh+swXuoCvXhQtpFEnd+94YT5XuMuJidnJU9s+GKcl/XU8nlguO3wnG9uFp3c454dHcGQAywksfler+9OTrjkSy+l3v+GWyLEjC2QlvYkP/o7ug0s/4H7z+U7vMZr5tMulzkiFhoNk7NVvgcyTh3x9HvgmJiabMFtx8WXISrAJUtKlgnPTMVZCZwAuTrGr95GfMOcCjTA==)
    username: ENC(mf26xrSdlsDGLOp2uRVtYQ==)
    password: ENC(B9/bakG1kuaw3NeCNI4dq6K/zkFiyO7uSWx6IR7jUQA=)

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
    hibernate:
      ddl-auto: validate
    generate-ddl: false