spring:
  profiles:
    group:
      local: aws, local_oauth, local_redis
      dev: aws, dev_oauth, dev_redis
    active: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 10
    hibernate:
      ddl-auto: create
    generate-ddl: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  data:
    web:
      pageable:
        default-page-size: 8

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}