version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./www:/var/www/html
    ports:
      - 80:80

    certbot:
      depends_on:
        - nginx
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./certbot/etc:/etc/letsencrypt
        - ./certbot/var:/var/lib/letsencrypt
        - ./www:/var/www/html
      command: certonly --webroot --webroot-path=/var/www/html --email sunghyuk1609@gmail.com --agree-tos --no-eff-email --force-renewal -d api.collusic.com

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      JASYPT_PASSWORD: ${JASYPT_PASSWORD}
    depends_on:
      - redis
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=dev